### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/Deployment#2]
When executing the run.sh file on the cloud instance there is an error

This is the log:

![image](https://user-images.githubusercontent.com/6508705/36625758-c2d7d31e-18f3-11e8-8d89-6a68a89928a7.png)

```make command not found```

It is solved using ```apt install make```

**Comment by amrondonp** [comment]
It is solved using ```apt install make```

**Comment by jesusfchavarro** [comment]
This error is because 2 things, the first is that you already run the script move the docker-compose.yml to $JUDGE_HOME define in deployment_configuration.env. The second thing is that the $JUDGE_HOME is "/tmp/Judge" by default(the best is that you use a no-root folder here), so, when you run by second time you don't have de file in the repository and maybe neither in /tmp/Judge and the command `docker-compose up` won't find the docker-compose.yml file

```bash
mv ./docker-compose.yml $JUDGE_HOME/docker-compose.yml
(cd $JUDGE_HOME && docker-compose up)
```
